name: init action

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  init-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: ./
